package Package;

import javax.swing.*;
import java.sql.*;
import java.util.ArrayList;


import javax.swing.JSpinner.DefaultEditor;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Wongsinsanity
 */
public class GUIClass extends javax.swing.JFrame {
    private String cDate;
    private String cName;
    //private static final String DEFAULT_QUERY = "SELECT * FROM BOOKING WHERE DATE = 2017-01-01";
    //SELECT name FROM JAVA.BOOKING WHERE date = 2017-01-01
    private static Table tableModel;
    public GUIClass(){
        /*     try {
        tableModel = new Table(DEFAULT_QUERY);
        } catch (SQLException ex) {
        ex.printStackTrace();
        }*/
        initComponents();
        flightCombo.setModel(new javax.swing.DefaultComboBoxModel(Flight.getMyFlights().toArray()));
        dateCombo.setModel(new javax.swing.DefaultComboBoxModel(getMyDate.getMyDate().toArray()));
        
       ((DefaultEditor)flightSeatsSpinner.getEditor()).getTextField().setEditable(false);
        addTextArea.setLineWrap(true);
        addTextArea.setWrapStyleWord(true);
    }

    public void setcName(String cName) {
        this.cName = cName;
    }
    public String getcName() {
        return cName;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bookingDialog = new javax.swing.JDialog();
        bookingDialog.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lastNameText = new javax.swing.JTextField();
        firstNameText = new javax.swing.JTextField();
        bookingConfirm = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        bookingCancel = new javax.swing.JButton();
        cancelDialog = new javax.swing.JDialog();
        cancelDialog.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lastNameCancel = new javax.swing.JTextField();
        firstNameCancel = new javax.swing.JTextField();
        cancelConfirm = new javax.swing.JButton();
        cancelWarning = new javax.swing.JLabel();
        cancelCancel = new javax.swing.JButton();
        cancelWarning1 = new javax.swing.JLabel();
        dropFDialog = new javax.swing.JDialog();
        dropFConfirm = new javax.swing.JButton();
        warningDropF = new javax.swing.JLabel();
        cancelDropF = new javax.swing.JButton();
        warningFlight = new javax.swing.JLabel();
        dropDDialog = new javax.swing.JDialog();
        dropDConfirm = new javax.swing.JButton();
        warningDropD = new javax.swing.JLabel();
        cancelDropD = new javax.swing.JButton();
        warningDate = new javax.swing.JLabel();
        addFlightDialog = new javax.swing.JDialog();
        addFConfirm = new javax.swing.JButton();
        warningAddF = new javax.swing.JLabel();
        cancelAddF = new javax.swing.JButton();
        warningAddFlight = new javax.swing.JLabel();
        addDateDialog = new javax.swing.JDialog();
        addDateConfirm = new javax.swing.JButton();
        warningAddD = new javax.swing.JLabel();
        cancelAddD = new javax.swing.JButton();
        warningAddDate = new javax.swing.JLabel();
        tablePanel = new javax.swing.JTabbedPane();
        addPannel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        addFText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        flightSeatsSpinner = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        addYear = new javax.swing.JComboBox<>();
        addMonth = new javax.swing.JComboBox<>();
        addDay = new javax.swing.JComboBox<>();
        addDateButton = new javax.swing.JButton();
        addFlightButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        addTextArea = new javax.swing.JTextArea();
        bookingPanel = new javax.swing.JPanel();
        booking = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookingText = new javax.swing.JTextArea();
        cancelButton = new javax.swing.JButton();
        dropFButton = new javax.swing.JButton();
        dropDButton = new javax.swing.JButton();
        statusPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        statusText = new javax.swing.JTextArea();
        flightStatus = new javax.swing.JButton();
        waitlistStatus = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        dayTag = new javax.swing.JLabel();
        dateCombo = new javax.swing.JComboBox<>();
        flightTag = new javax.swing.JLabel();
        flightCombo = new javax.swing.JComboBox<>();

        jLabel4.setText("First Name: ");

        jLabel5.setText("Last Name");

        lastNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTextActionPerformed(evt);
            }
        });

        firstNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextActionPerformed(evt);
            }
        });

        bookingConfirm.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        bookingConfirm.setText("Confirm");
        bookingConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingConfirmActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Please Enter Your Info");

        bookingCancel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        bookingCancel.setText("Cancel");
        bookingCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bookingDialogLayout = new javax.swing.GroupLayout(bookingDialog.getContentPane());
        bookingDialog.getContentPane().setLayout(bookingDialogLayout);
        bookingDialogLayout.setHorizontalGroup(
            bookingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookingDialogLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jLabel6)
                .addContainerGap(130, Short.MAX_VALUE))
            .addGroup(bookingDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bookingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bookingConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bookingDialogLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(firstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(bookingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bookingDialogLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(lastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bookingCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        bookingDialogLayout.setVerticalGroup(
            bookingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookingDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(bookingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(firstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(bookingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookingConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookingCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        jLabel7.setText("First Name: ");

        jLabel9.setText("Last Name");

        lastNameCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameCancelActionPerformed(evt);
            }
        });

        firstNameCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameCancelActionPerformed(evt);
            }
        });

        cancelConfirm.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cancelConfirm.setText("Confirm");
        cancelConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelConfirmActionPerformed(evt);
            }
        });

        cancelWarning.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cancelWarning.setText("Are You Sure About Canceling");

        cancelCancel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cancelCancel.setText("Cancel");
        cancelCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelCancelActionPerformed(evt);
            }
        });

        cancelWarning1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cancelWarning1.setText("Your Flight");

        javax.swing.GroupLayout cancelDialogLayout = new javax.swing.GroupLayout(cancelDialog.getContentPane());
        cancelDialog.getContentPane().setLayout(cancelDialogLayout);
        cancelDialogLayout.setHorizontalGroup(
            cancelDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cancelDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cancelDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cancelDialogLayout.createSequentialGroup()
                        .addGroup(cancelDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cancelConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(cancelDialogLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(firstNameCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(cancelDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cancelDialogLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(lastNameCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cancelCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(cancelDialogLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(cancelDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cancelWarning)
                            .addGroup(cancelDialogLayout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(cancelWarning1)))
                        .addContainerGap(85, Short.MAX_VALUE))))
        );
        cancelDialogLayout.setVerticalGroup(
            cancelDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cancelDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cancelWarning)
                .addGap(18, 18, 18)
                .addComponent(cancelWarning1)
                .addGap(42, 42, 42)
                .addGroup(cancelDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(firstNameCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(cancelDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        dropFDialog.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);

        dropFConfirm.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        dropFConfirm.setText("Confirm");
        dropFConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropFConfirmActionPerformed(evt);
            }
        });

        warningDropF.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        warningDropF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        warningDropF.setText("Are You Sure About Dropping");
        warningDropF.setToolTipText("");

        cancelDropF.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cancelDropF.setText("Cancel");
        cancelDropF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelDropFActionPerformed(evt);
            }
        });

        warningFlight.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        warningFlight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        warningFlight.setText("to be changed");
        warningFlight.setToolTipText("");
        warningFlight.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout dropFDialogLayout = new javax.swing.GroupLayout(dropFDialog.getContentPane());
        dropFDialog.getContentPane().setLayout(dropFDialogLayout);
        dropFDialogLayout.setHorizontalGroup(
            dropFDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dropFDialogLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(dropFConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addComponent(cancelDropF, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
            .addGroup(dropFDialogLayout.createSequentialGroup()
                .addGroup(dropFDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dropFDialogLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(warningDropF))
                    .addGroup(dropFDialogLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(warningFlight)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dropFDialogLayout.setVerticalGroup(
            dropFDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dropFDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(warningDropF, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(warningFlight, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                .addGap(78, 78, 78)
                .addGroup(dropFDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dropFConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelDropF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        dropDDialog.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);

        dropDConfirm.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        dropDConfirm.setText("Confirm");
        dropDConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropDConfirmActionPerformed(evt);
            }
        });

        warningDropD.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        warningDropD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        warningDropD.setText("Are You Sure About Dropping");
        warningDropD.setToolTipText("");

        cancelDropD.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cancelDropD.setText("Cancel");
        cancelDropD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelDropDActionPerformed(evt);
            }
        });

        warningDate.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        warningDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        warningDate.setText("to be changed");
        warningDate.setToolTipText("");
        warningDate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout dropDDialogLayout = new javax.swing.GroupLayout(dropDDialog.getContentPane());
        dropDDialog.getContentPane().setLayout(dropDDialogLayout);
        dropDDialogLayout.setHorizontalGroup(
            dropDDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dropDDialogLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(dropDConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addComponent(cancelDropD, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
            .addGroup(dropDDialogLayout.createSequentialGroup()
                .addGroup(dropDDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dropDDialogLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(warningDropD))
                    .addGroup(dropDDialogLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(warningDate)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dropDDialogLayout.setVerticalGroup(
            dropDDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dropDDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(warningDropD, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(warningDate, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                .addGap(78, 78, 78)
                .addGroup(dropDDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dropDConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelDropD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        addFlightDialog.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);

        addFConfirm.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        addFConfirm.setText("Confirm");
        addFConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFConfirmActionPerformed(evt);
            }
        });

        warningAddF.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        warningAddF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        warningAddF.setText("You Are Adding Flight:");
        warningAddF.setToolTipText("");

        cancelAddF.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cancelAddF.setText("Cancel");
        cancelAddF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelAddFActionPerformed(evt);
            }
        });

        warningAddFlight.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        warningAddFlight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        warningAddFlight.setText("to be changed");
        warningAddFlight.setToolTipText("");
        warningAddFlight.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout addFlightDialogLayout = new javax.swing.GroupLayout(addFlightDialog.getContentPane());
        addFlightDialog.getContentPane().setLayout(addFlightDialogLayout);
        addFlightDialogLayout.setHorizontalGroup(
            addFlightDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addFlightDialogLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(addFConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addComponent(cancelAddF, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
            .addGroup(addFlightDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(warningAddFlight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addFlightDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(warningAddF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        addFlightDialogLayout.setVerticalGroup(
            addFlightDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addFlightDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(warningAddF, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(warningAddFlight, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                .addGap(90, 90, 90)
                .addGroup(addFlightDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addFConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelAddF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        addDateDialog.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);

        addDateConfirm.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        addDateConfirm.setText("Confirm");
        addDateConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDateConfirmActionPerformed(evt);
            }
        });

        warningAddD.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        warningAddD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        warningAddD.setText("You Are Adding Date:");
        warningAddD.setToolTipText("");

        cancelAddD.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cancelAddD.setText("Cancel");
        cancelAddD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelAddDActionPerformed(evt);
            }
        });

        warningAddDate.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        warningAddDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        warningAddDate.setText("to be changed");
        warningAddDate.setToolTipText("");
        warningAddDate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout addDateDialogLayout = new javax.swing.GroupLayout(addDateDialog.getContentPane());
        addDateDialog.getContentPane().setLayout(addDateDialogLayout);
        addDateDialogLayout.setHorizontalGroup(
            addDateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addDateDialogLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(addDateConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addComponent(cancelAddD, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
            .addGroup(addDateDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(warningAddD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addDateDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(warningAddDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        addDateDialogLayout.setVerticalGroup(
            addDateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addDateDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(warningAddD, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(warningAddDate, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                .addGap(90, 90, 90)
                .addGroup(addDateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addDateConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelAddD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Flight Name:");

        addFText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addFText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFTextActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Seats:");

        flightSeatsSpinner.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        flightSeatsSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 999, 1));
        flightSeatsSpinner.setToolTipText("");
        flightSeatsSpinner.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Month:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel10.setText("Year:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel11.setText("Day:");

        addYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2016", "2017", "2018", "2019", "2020", "2021" }));
        addYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addYearActionPerformed(evt);
            }
        });

        addMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        addMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMonthActionPerformed(evt);
            }
        });

        addDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        addDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDayActionPerformed(evt);
            }
        });

        addDateButton.setText("Add Date");
        addDateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDateButtonActionPerformed(evt);
            }
        });

        addFlightButton.setText("Add Flight");
        addFlightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFlightButtonActionPerformed(evt);
            }
        });

        addTextArea.setEditable(false);
        addTextArea.setColumns(20);
        addTextArea.setRows(5);
        addTextArea.setPreferredSize(new java.awt.Dimension(150, 90));
        jScrollPane3.setViewportView(addTextArea);

        javax.swing.GroupLayout addPannelLayout = new javax.swing.GroupLayout(addPannel);
        addPannel.setLayout(addPannelLayout);
        addPannelLayout.setHorizontalGroup(
            addPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPannelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(addPannelLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addDay, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(addPannelLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addMonth, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(addPannelLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addYear, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(addPannelLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(flightSeatsSpinner))
                    .addGroup(addPannelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addFText, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addDateButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addFlightButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        addPannelLayout.setVerticalGroup(
            addPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPannelLayout.createSequentialGroup()
                .addGroup(addPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPannelLayout.createSequentialGroup()
                        .addGroup(addPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addPannelLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(addFlightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(addPannelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(addPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addFText, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(addPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(flightSeatsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(addPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addYear, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(addPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addDateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(addPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addDay, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(addPannelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3)))
                .addGap(27, 27, 27))
        );

        tablePanel.addTab("Add", addPannel);

        booking.setText("Book");
        booking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookingMouseClicked(evt);
            }
        });
        booking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingActionPerformed(evt);
            }
        });

        bookingText.setEditable(false);
        bookingText.setColumns(20);
        bookingText.setRows(5);
        jScrollPane1.setViewportView(bookingText);

        cancelButton.setText("Cancel");
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelButtonMouseClicked(evt);
            }
        });
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        dropFButton.setText("Drop Flight");
        dropFButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dropFButtonMouseClicked(evt);
            }
        });
        dropFButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropFButtonActionPerformed(evt);
            }
        });

        dropDButton.setText("Drop Date");
        dropDButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dropDButtonMouseClicked(evt);
            }
        });
        dropDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropDButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bookingPanelLayout = new javax.swing.GroupLayout(bookingPanel);
        bookingPanel.setLayout(bookingPanelLayout);
        bookingPanelLayout.setHorizontalGroup(
            bookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
                    .addGroup(bookingPanelLayout.createSequentialGroup()
                        .addComponent(booking, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(dropFButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(dropDButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        bookingPanelLayout.setVerticalGroup(
            bookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(booking, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dropFButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dropDButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addContainerGap())
        );

        tablePanel.addTab("Flight Command", bookingPanel);

        statusText.setEditable(false);
        statusText.setColumns(20);
        statusText.setRows(5);
        jScrollPane2.setViewportView(statusText);

        flightStatus.setText("Flight Status");
        flightStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flightStatusActionPerformed(evt);
            }
        });

        waitlistStatus.setText("Waitlist Status");
        waitlistStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waitlistStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout statusPanelLayout = new javax.swing.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(flightStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 221, Short.MAX_VALUE)
                .addComponent(waitlistStatus)
                .addGap(75, 75, 75))
        );
        statusPanelLayout.setVerticalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(flightStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(waitlistStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tablePanel.addTab("Flight Status", statusPanel);

        jLabel8.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(3, 94, 225));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Not United Airline");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        dayTag.setText("Date");

        dateCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30","31" }));
        dateCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateComboActionPerformed(evt);
            }
        });

        flightTag.setText("Flights");

        flightCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flightComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(dayTag)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120)
                        .addComponent(flightTag)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(flightCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tablePanel))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dayTag)
                    .addComponent(dateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(flightTag)
                    .addComponent(flightCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dateComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateComboActionPerformed

    }//GEN-LAST:event_dateComboActionPerformed

    private void lastNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTextActionPerformed

    private void firstNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextActionPerformed

    private void bookingConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingConfirmActionPerformed

        String name = firstNameText.getText() + " " + lastNameText.getText();
        setcName(name);
        //System.out.printf("%s", name);
        lastNameText.setText("");
        firstNameText.setText("");
        bookingText.setText("");
        if(flightCombo.getItemCount() == 0 || dateCombo.getItemCount() == 0)
        {
            bookingText.setText("No Flights or Dates available.");
        }
        else
        {
            Booking.Booking(getcName(),(String)flightCombo.getSelectedItem(), (Date)dateCombo.getSelectedItem(),0);
        }
        this.setEnabled(true);
        bookingDialog.dispose();
    }//GEN-LAST:event_bookingConfirmActionPerformed

    private void flightComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flightComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flightComboActionPerformed

    private void bookingCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingCancelActionPerformed
        this.setEnabled(true);
        lastNameText.setText("");
        firstNameText.setText("");
        bookingDialog.dispose();
    }//GEN-LAST:event_bookingCancelActionPerformed

    private void lastNameCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameCancelActionPerformed

    private void firstNameCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameCancelActionPerformed

    private void cancelConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelConfirmActionPerformed

        String name = firstNameCancel.getText() + " " + lastNameCancel.getText();
        setcName(name);
        //System.out.printf("%s", name);
        firstNameCancel.setText("");
        lastNameCancel.setText("");
        bookingText.setText("");
        
        Cancel.Cancel(getcName(),(Date)dateCombo.getSelectedItem(),(String)flightCombo.getSelectedItem());
        this.setEnabled(true);
        cancelDialog.dispose();
    }//GEN-LAST:event_cancelConfirmActionPerformed

    private void cancelCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelCancelActionPerformed
        this.setEnabled(true);

        cancelDialog.dispose();
    }//GEN-LAST:event_cancelCancelActionPerformed

    private void dropFConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropFConfirmActionPerformed
        bookingText.setText("");

        DeleteFlight.DeleteFlight((String)flightCombo.getSelectedItem());

        flightCombo.setModel(new javax.swing.DefaultComboBoxModel(Flight.getMyFlights().toArray()));
        this.setEnabled(true);
        dropFDialog.dispose();
    }//GEN-LAST:event_dropFConfirmActionPerformed

    private void cancelDropFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelDropFActionPerformed
        this.setEnabled(true);
        dropFDialog.dispose();
    }//GEN-LAST:event_cancelDropFActionPerformed

    private void dropDConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropDConfirmActionPerformed
        bookingText.setText("");

        DeleteDate.DeleteDate((Date)dateCombo.getSelectedItem());
        dateCombo.setModel(new javax.swing.DefaultComboBoxModel(getMyDate.getMyDate().toArray()));
        this.setEnabled(true);
        dropDDialog.dispose();
    }//GEN-LAST:event_dropDConfirmActionPerformed

    private void cancelDropDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelDropDActionPerformed
        this.setEnabled(true);
        dropDDialog.dispose();
    }//GEN-LAST:event_cancelDropDActionPerformed

    private void waitlistStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waitlistStatusActionPerformed
        statusText.setText("");
        if(flightCombo.getItemCount() == 0 || dateCombo.getItemCount() == 0)
        {
            statusText.setText("No Registration yet.");
        }
        else
        {
            waitList.WaitlistStatus((String) flightCombo.getSelectedItem(),(Date)dateCombo.getSelectedItem());
        }
    }//GEN-LAST:event_waitlistStatusActionPerformed

    private void flightStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flightStatusActionPerformed
        statusText.setText("");

        if(flightCombo.getItemCount() == 0 || dateCombo.getItemCount() == 0)
        {
            statusText.setText("No Registration yet.");
        }
        else
        {
            Booking.FlightStatus((String)flightCombo.getSelectedItem(), (Date)dateCombo.getSelectedItem());
        }
    }//GEN-LAST:event_flightStatusActionPerformed

    private void dropDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropDButtonActionPerformed
        if(dateCombo.getItemCount() == 0)
        {
            bookingText.setText("No Dates available.");
        }
        else
        {
            dropDDialog.setLocationRelativeTo(this);
            dropDDialog.setSize(500, 310);
            dropDDialog.setVisible(true);
            warningDate.setText("Date: " + (dateCombo.getSelectedItem()).toString()+ " From DB?");
            this.setEnabled(false);
        }

    }//GEN-LAST:event_dropDButtonActionPerformed

    private void dropDButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dropDButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dropDButtonMouseClicked

    private void dropFButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropFButtonActionPerformed
        if(flightCombo.getItemCount() == 0)
        {
            bookingText.setText("No Flights available.");
        }
        else
        {
            dropFDialog.setLocationRelativeTo(this);
            dropFDialog.setSize(500, 310);
            dropFDialog.setVisible(true);
            warningFlight.setText("Flight " + (String)(flightCombo.getSelectedItem())+ " From DB?");
            this.setEnabled(false);
        }
    }//GEN-LAST:event_dropFButtonActionPerformed

    private void dropFButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dropFButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dropFButtonMouseClicked

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        cancelDialog.setLocationRelativeTo(this);
        cancelDialog.setSize(500, 310);
        cancelDialog.setVisible(true);

        this.setEnabled(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void cancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelButtonMouseClicked

    private void bookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingActionPerformed

        bookingDialog.setLocationRelativeTo(this);
        bookingDialog.setSize(500, 310);
        bookingDialog.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_bookingActionPerformed

    private void bookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingMouseClicked
        //JOptionPane.showConfirmDialog(null, "Do you really?", "Confirmation", JOptionPane.YES_NO_OPTION);        // TODO add your handling code here:
        //jPopupMenu1 popup = new jPopupMenu1();
    }//GEN-LAST:event_bookingMouseClicked

    private void addFTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addFTextActionPerformed

    private void addYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addYearActionPerformed
        String year = (String)addYear.getSelectedItem();
        String month = (String)addMonth.getSelectedItem();
        if(month == "01"|| month =="03" ||  month =="05" ||  month =="07" || month =="08" || month =="10" || month =="12")
        {
            addDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"01","02","03","04","05","06","07","08","09","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31"}));
        }
        else
        {
            addDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"01","02","03","04","05","06","07","08","09","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30"}));
        }
        if(Integer.parseInt(year) % 4 == 0 && Integer.parseInt(year) % 100 != 0 && month == "02")
        {
            addDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"01","02","03","04","05","06","07","08","09","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29"}));

        }
        else if(month == "02")
        {
            addDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"01","02","03","04","05","06","07","08","09","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28"}));
        }   
    }//GEN-LAST:event_addYearActionPerformed

    private void addDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDayActionPerformed

    }//GEN-LAST:event_addDayActionPerformed

    private void addMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMonthActionPerformed
        String year = (String)addYear.getSelectedItem();
        String month = (String)addMonth.getSelectedItem();
        if(month == "01"|| month =="03" ||  month =="05" ||  month =="07" || month =="08" || month =="10" || month =="12")
        {
            addDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"01","02","03","04","05","06","07","08","09","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31"}));
        }
        else
        {
            addDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"01","02","03","04","05","06","07","08","09","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30"}));
        }
        if(Integer.parseInt(year) % 4 == 0 && Integer.parseInt(year) % 100 != 0 && month == "02")
        {
            addDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"01","02","03","04","05","06","07","08","09","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29"}));

        }
        else if(month == "02")
        {
            addDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"01","02","03","04","05","06","07","08","09","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28"}));
        }   
    }//GEN-LAST:event_addMonthActionPerformed

    private void addFlightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFlightButtonActionPerformed
        addFlightDialog.setLocationRelativeTo(this);
        addFlightDialog.setSize(500, 310);
        addFlightDialog.setVisible(true);
        warningAddFlight.setText(addFText.getText() + ". With " + (Integer)flightSeatsSpinner.getValue() + " seat/seats.");
        addTextArea.setText("");
        this.setEnabled(false);
    }//GEN-LAST:event_addFlightButtonActionPerformed

    private void addFConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFConfirmActionPerformed
        String flightName;
        int seats;
        flightName = addFText.getText();
        seats = (Integer)flightSeatsSpinner.getValue();
        ArrayList<String> myFlights = Flight.getMyFlights();
        if(myFlights.contains(flightName))
        {
            addTextArea.setText("No duplicated flights allowed. Flight was already added.");
        }
        else
        {
            addFlight.addFlight(flightName, seats);
            addFText.setText("");
            addTextArea.setText("Your Flight: " + flightName + " Is Added To The Database.");
            flightCombo.setModel(new javax.swing.DefaultComboBoxModel(Flight.getMyFlights().toArray()));
        }
        this.setEnabled(true);
        addFlightDialog.dispose();
    }//GEN-LAST:event_addFConfirmActionPerformed

    private void cancelAddFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelAddFActionPerformed
        this.setEnabled(true);
        addFlightDialog.dispose();
    }//GEN-LAST:event_cancelAddFActionPerformed

    private void addDateConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDateConfirmActionPerformed
        String date = (String)addYear.getSelectedItem() + "-" + (String)addMonth.getSelectedItem() +"-"+ (String)addDay.getSelectedItem();
        Date theDate = java.sql.Date.valueOf(date);
        ArrayList<Date> myDates = getMyDate.getMyDate();
        if(myDates.contains(theDate))
        {
            addTextArea.setText("No duplicated dates allowed. Date was already added.");
        }
        else
        {
            addDate.addDate(theDate);
            addTextArea.setText("Your Date: " + date + " Is Added To The Database.");
            dateCombo.setModel(new javax.swing.DefaultComboBoxModel(getMyDate.getMyDate().toArray()));
        }
        this.setEnabled(true);
        addDateDialog.dispose();
    }//GEN-LAST:event_addDateConfirmActionPerformed

    private void cancelAddDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelAddDActionPerformed
        this.setEnabled(true);
        addDateDialog.dispose();
    }//GEN-LAST:event_cancelAddDActionPerformed

    private void addDateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDateButtonActionPerformed
        addDateDialog.setLocationRelativeTo(this);
        addDateDialog.setSize(500, 310);
        addDateDialog.setVisible(true);
        warningAddDate.setText((String)addYear.getSelectedItem() + "/" + (String)addMonth.getSelectedItem() +"/"+ (String)addDay.getSelectedItem());
        addTextArea.setText("");
        this.setEnabled(false);
    }//GEN-LAST:event_addDateButtonActionPerformed
    public static void updateBookingText(String a){
        bookingText.append(a);
    }
    public static void insertAreaStatus(String a){
        statusText.append(a);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GUIClass().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDateButton;
    private javax.swing.JButton addDateConfirm;
    private javax.swing.JDialog addDateDialog;
    private javax.swing.JComboBox<String> addDay;
    private javax.swing.JButton addFConfirm;
    private javax.swing.JTextField addFText;
    private javax.swing.JButton addFlightButton;
    private javax.swing.JDialog addFlightDialog;
    private javax.swing.JComboBox<String> addMonth;
    private javax.swing.JPanel addPannel;
    private javax.swing.JTextArea addTextArea;
    private javax.swing.JComboBox<String> addYear;
    private javax.swing.JButton booking;
    private javax.swing.JButton bookingCancel;
    private javax.swing.JButton bookingConfirm;
    private javax.swing.JDialog bookingDialog;
    private javax.swing.JPanel bookingPanel;
    private static javax.swing.JTextArea bookingText;
    private javax.swing.JButton cancelAddD;
    private javax.swing.JButton cancelAddF;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton cancelCancel;
    private javax.swing.JButton cancelConfirm;
    private javax.swing.JDialog cancelDialog;
    private javax.swing.JButton cancelDropD;
    private javax.swing.JButton cancelDropF;
    private javax.swing.JLabel cancelWarning;
    private javax.swing.JLabel cancelWarning1;
    private javax.swing.JComboBox<String> dateCombo;
    private javax.swing.JLabel dayTag;
    private javax.swing.JButton dropDButton;
    private javax.swing.JButton dropDConfirm;
    private javax.swing.JDialog dropDDialog;
    private javax.swing.JButton dropFButton;
    private javax.swing.JButton dropFConfirm;
    private javax.swing.JDialog dropFDialog;
    private javax.swing.JTextField firstNameCancel;
    private javax.swing.JTextField firstNameText;
    private javax.swing.JComboBox<String> flightCombo;
    private javax.swing.JSpinner flightSeatsSpinner;
    private javax.swing.JButton flightStatus;
    private javax.swing.JLabel flightTag;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField lastNameCancel;
    private javax.swing.JTextField lastNameText;
    private javax.swing.JPanel statusPanel;
    private static javax.swing.JTextArea statusText;
    private javax.swing.JTabbedPane tablePanel;
    private javax.swing.JButton waitlistStatus;
    private javax.swing.JLabel warningAddD;
    private javax.swing.JLabel warningAddDate;
    private javax.swing.JLabel warningAddF;
    private javax.swing.JLabel warningAddFlight;
    private javax.swing.JLabel warningDate;
    private javax.swing.JLabel warningDropD;
    private javax.swing.JLabel warningDropF;
    private javax.swing.JLabel warningFlight;
    // End of variables declaration//GEN-END:variables
}
